"use strict";
const machines=["Komatsu WA500-6","Komatsu WA800-3","Komatsu WA1200-6","Komatsu LeTourneau L2350"];
const modules=[
["Plan and prepare","Interpret work requirements, drawings, permits, SWMS, site controls and civil specifications.",["Apply duties under the Work Health and Safety Act 2011 (Qld) and the hierarchy of controls.","Reconcile work orders, drawings, ITP, SWMS, traffic plans, service information, permits and handover.","Treat BYDA plans as indicative; locate, mark and pothole services under site controls.","Report fatigue, illness, medication effects or impairment before operating."]],
["Machine and work-area readiness","Select a suitable loader, inspect the area, complete pre-starts and respond to defects.",["Confirm the loader and attachment suit the task using controlled OEM information.","Inspect access, ROPS/FOPS, restraint, tyres, articulation, brakes, alarms, cameras, fluids, leaks and implements.","Keep people outside articulation and implement crush zones; fit the articulation lock before authorised centre-pivot work.","Stop safely, isolate when required, tag and report faults."]],
["Materials and calculations","Apply material knowledge, load calculations and civil quality requirements.",["Estimate load mass as volume × density × fill factor.","Reassess technique when moisture changes density, cohesion, traction or compaction response.","Spread to specified layer thickness and moisture; loader placement does not replace testing.","Use drawings, survey control, tolerances and ITP hold points."]],
["Operate and load","Operate safely while monitoring people, plant, ground and machine performance.",["Travel with the implement as low as safely practicable.","Load receiving vehicles evenly and within approved limits.","Stop when a signal is unclear, communication is lost or a person enters the exclusion zone.","Respond to warnings under approved OEM and site procedures."]],
["Civil production tasks","Complete mandatory civil work sequences to specification.",["Mix to the approved specification while controlling contamination and segregation.","Strip and spread in controlled layers while protecting services and survey marks.","Cut, box and trim to drawings and survey control.","Backfill under the specified material, layer and compaction sequence."]],
["Float, transport and attachments","Assist with float loading and manage authorised attachments.",["Confirm authority, transport plan, mass, dimensions, capacity, ground bearing, restraints and clearances.","Use an exclusion zone and one nominated spotter.","Use only approved compatible attachments.","Each party must discharge their safety and chain-of-responsibility duties."]],
["Shutdown and environment","Park, secure, inspect and complete environmental controls.",["Park on a stable designated area, lower the implement, brake, idle and shut down as required.","Stop oil, fuel and sediment entering land, drains or waters.","Separate waste under the site plan.","Complete timely inspection, fault, production and handover records."]],
["Assessment readiness","Prepare for theory and two assessor-observed practical occasions.",["Complete all specified civil tasks twice using at least two material types.","Use a safe sector-relevant environment, current procedures, manuals, equipment, materials and PPE.","Reasonable adjustment cannot remove mandatory skills, compromise safety or lower the standard.","A credentialed assessor verifies identity, authenticity and evidence and makes the decision."]]
];
const questions=[
["BYDA information indicates a service may be present. What must happen before loader work enters the affected area?",["Proceed slowly using bucket feel","Confirm location and required controls under the permit and site procedure","Stay an estimated five metres away","Ask a truck driver"],1,"PE: documentation, hazards and safe work practices"],
["A candidate completes every online question correctly. What does this prove?",["Full RIIMPO321F competency","Practical competency only","Theory mastery only; practical evidence and assessor judgement remain required","A licence to operate"],2,"ASQA Standards 1.3–1.4"],
["Which calculation estimates load mass?",["Bucket volume × material density","Tyre pressure × travel speed","Engine power ÷ bucket width","Distance × fuel use"],0,"KE: calculations and material characteristics"],
["What is the correct authority for a nominated loader’s operating capacity?",["The last operator’s estimate","An internet specification","The approved OEM manual, load chart and site procedure for that configuration","Bucket appearance"],2,"PE: equipment capability and limitations"],
["Which evidence is mandatory for practical assessment?",["One simulated quiz","Two operating occasions using at least two material types and specified civil tasks","A supervisor reference only","A video watched twice"],1,"RIIMPO321F Performance Evidence"],
["When travelling with a load, the bucket should generally be:",["Raised for visibility","As low as safely practicable under the OEM manual and site conditions","In float","At maximum height"],1,"PE: driving and operating techniques"],
["A worker enters the loader exclusion zone and eye contact is lost. What is the immediate response?",["Sound the horn and continue","Stop, secure as required and re-establish positive communication","Reverse quickly","Raise the bucket"],1,"PC: monitor hazards and ensure safety"],
["Which statement about fatigue is correct?",["Fatigue need not be reported","Coffee removes the risk","Follow fitness-for-work procedures and report impairment before operating","Only night shift creates fatigue"],2,"KE: fatigue signs and management"],
["Why must a truck not be corrected for lean by loading extra material on one side?",["It takes longer","It can destabilise the truck and create mass-distribution risks","It changes paint wear","It reduces loader fuel"],1,"PE: loading and chain of responsibility"],
["What controls trimming and levelling acceptance on a civil site?",["What looks flat from the cab","Survey control, drawings, tolerances and the ITP","Loader tyre tracks","Previous stockpile height"],1,"KE: drawings and civil quality"],
["How should a critical warning or abnormal condition be handled?",["Clear the code","Follow OEM/site response, stop safely and report within authorisation","Ask later","Increase engine speed"],1,"PE: alarms and common faults"],
["Before assisting with loading or unloading from a float, confirm:",["Only the float colour","Authorisation, plan, ground capacity, ramps, exclusion zone, restraints and signals","A full bucket","No spotter"],1,"PE: float/trailer loading"],
["How should hydraulic oil near a stormwater inlet be managed?",["Hose it away","Contain it, protect drainage, report and dispose correctly","Cover and leave it","Mix it into soil"],1,"KE/PE: environment and housekeeping"],
["Reasonable adjustment may be provided when it:",["Removes a mandatory task","Changes the standard","Supports access without compromising the training product or safety","Lets another person complete it"],2,"Outcome Standard 2.4"],
["Who makes the final competency judgement?",["The app","The candidate","An appropriately credentialed assessor using valid, sufficient, authentic and current evidence","The dealer"],2,"ASQA Standard 1.4 and Credential Policy"],
["Which set contains all mandatory civil-production categories?",["Loading only","Mixing; stripping/spreading; loading; cutting/boxing; backfilling; lifting/carrying; clean-up; parking/securing","Driving and refuelling only","Stockpiling only"],1,"RIIMPO321F Performance Evidence"]
];
const tasks=["Confirmed work requirements, drawings, specifications, SWMS, permits and communications","Selected PPE and inspected hazards and environmental controls","Completed documented pre-start and start-up to the OEM manual","Operated for ground, weather, traffic and material conditions","Monitored indicators and responded to faults","Mixed materials to specification","Stripped and spread to line, level and thickness","Loaded receiving plant with controlled distribution","Completed cutting or boxing to drawings and survey","Backfilled while controlling services and trench-edge risk","Lifted and carried within rated capacity","Assisted with float/trailer loading and unloading","Applied levelling and checked specification","Established load weight using volume, density and approved information","Used agreed hand, audible and radio signals","Completed clean-up, waste and environmental controls","Parked, shut down, secured and inspected","Completed records, fault reports and handover"];
const sources=[["training.gov.au RIIMPO321F Release 3","Unit requirements, assessment requirements and mapping"],["Standards for RTOs 2025","Outcome Standards and assessment governance"],["Work Health and Safety Act 2011 (Qld)","Primary Queensland WHS duties"],["Work Health and Safety Regulation 2011 (Qld)","Risk management, construction and plant"],["Managing the risks of plant in the workplace Code of Practice 2021","Plant hazards and controls"],["Excavation work Code of Practice 2021","Excavations, trenches, services and mobile plant"],["Electrical Safety Act 2002 (Qld) and applicable regulation","Electrical duties; verify currency before delivery"],["Environmental Protection Act 1994 (Qld)","General environmental duty"],["Heavy Vehicle National Law (Queensland)","Transport and chain-of-responsibility duties"],["Approved OEM and site-controlled documents","Model-specific limits and operating procedures"]];
const newOccasion=()=>({date:"",location:"",machine:machines[0],serial:"",material:"",assessor:"",tasks:Array(tasks.length).fill(false),critical:false,comments:"",candidateDeclaration:false,assessorDeclaration:false});
const defaults={view:"overview",candidate:{name:"",id:""},completed:[],badges:[],answers:{},submitted:false,occasions:[newOccasion(),newOccasion()]};
let state=load();let transient={hotspots:[],height:55,sequence:[],calc:{volume:5.6,density:1.8,fill:90,capacity:11}};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem("riimpo321f-github")||"{}")}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem("riimpo321f-github",JSON.stringify(state));updateProgress()}
const score=()=>questions.filter((q,i)=>state.answers[i]===q[2]).length;
const occasionComplete=o=>Boolean(o.date&&o.location&&o.serial&&o.material&&o.assessor&&o.tasks.every(Boolean)&&!o.critical&&o.candidateDeclaration&&o.assessorDeclaration);
const practicalPassed=()=>state.occasions.every(occasionComplete)&&new Set(state.occasions.map(o=>o.material.trim().toLowerCase())).size>=2;
const theoryPassed=()=>state.submitted&&score()===questions.length;
function updateProgress(){const p=Math.min(100,Math.round(state.completed.length/8*20+state.badges.length/4*10+score()/16*30+state.occasions.filter(occasionComplete).length/2*40));document.querySelector("#progressText").textContent=p+"%";document.querySelector("#progressBar").style.width=p+"%"}
function notice(text){const n=document.querySelector("#notice");n.textContent=text;n.hidden=false;clearTimeout(notice.t);notice.t=setTimeout(()=>n.hidden=true,3000)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function go(view){state.view=view;save();document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));document.querySelector("#pageTitle").textContent=document.querySelector(`[data-view="${view}"]`).textContent.replace(/^\d+/,"");render();window.scrollTo(0,0)}
function render(){const c=document.querySelector("#content");c.innerHTML=views[state.view]();bind()}
const views={
overview:()=>`<section class="content"><div class="hero"><div><span class="eyebrow">Training + authenticated assessment workflow</span><h2>Conduct civil construction wheeled front end loader operations</h2><p>A Queensland-contextualised pathway combining structured learning, visual practice, 100% theory mastery and assessor-observed evidence.</p><div class="actions"><button class="primary" data-go="training">Continue program</button><button data-go="practical">Open assessor tools</button></div></div><div class="hero-stat"><strong>${theoryPassed()&&practicalPassed()?"Ready":"In progress"}</strong><span>for assessor judgement</span><small>Software never awards competency automatically.</small></div></div><div class="metrics"><article><span>Training</span><strong>${state.completed.length}/8</strong><small>modules complete</small></article><article><span>Theory</span><strong>${state.submitted?score()+"/16":"Not submitted"}</strong><small>100% mastery required</small></article><article><span>Practical</span><strong>${state.occasions.filter(occasionComplete).length}/2</strong><small>observed occasions</small></article><article><span>Evidence gate</span><strong>${theoryPassed()&&practicalPassed()?"Open":"Locked"}</strong><small>assessor decision required</small></article></div><div class="panel split"><div><h3>Mandatory evidence</h3><ul><li>Two operating occasions</li><li>At least two material types</li><li>All mandatory civil tasks</li><li>Authenticated declarations</li></ul></div><div class="warning"><strong>Competency safeguard</strong><p>Completion and scores support learning. Only an appropriately credentialed assessor may make and record the final judgement.</p></div></div></section>`,
training:()=>`<section class="content"><div class="section-intro"><span class="eyebrow">Eight-part learning pathway</span><h2>Essential learning</h2><p>Complete each module after reviewing the outcome and essential points. Delivery must also use current site procedures and controlled OEM manuals.</p></div><div class="module-grid">${modules.map((m,i)=>`<article class="module ${state.completed.includes(i)?"done":""}"><span class="eyebrow">Module ${i+1}</span><h3>${m[0]}</h3><p>${m[1]}</p><details><summary>Review essential learning</summary><ul>${m[2].map(x=>`<li>${x}</li>`).join("")}</ul></details><button data-module="${i}">${state.completed.includes(i)?"Completed ✓":"Mark complete"}</button></article>`).join("")}</div></section>`,
practice:()=>`<section class="content"><div class="section-intro"><span class="eyebrow">Visual learning activities</span><h2>Practice zone</h2><p>Explore the safety concepts. These activities are formative and do not replace assessment evidence.</p></div><div class="activity-grid"><article class="activity"><span class="eyebrow">Challenge 1</span><h3>Pre-start hotspot hunt</h3><p>Find tyres, cab/seatbelt, articulation zone and bucket/attachment.</p><div class="scene"><img src="assets/loader-prestart.png" alt="Wheeled front end loader for pre-start inspection">${[[12,73,"Tyres"],[76,16,"Cab"],[59,57,"Articulation"],[28,70,"Bucket"]].map((h,i)=>`<button class="hotspot ${transient.hotspots.includes(i)?"found":""}" data-hotspot="${i}" style="left:${h[0]}%;top:${h[1]}%" aria-label="${h[2]}">${transient.hotspots.includes(i)?"✓":"+"}</button>`).join("")}</div></article><article class="activity"><span class="eyebrow">Challenge 2</span><h3>Bucket-height stability</h3><p>Move the bucket height and observe the centre-of-gravity risk.</p><div class="motion"><img id="motionImg" src="assets/komatsu-wa500.png" alt="Komatsu WA500 loader" style="transform:rotate(${(transient.height-50)/30}deg) scale(${1+transient.height/1000})"></div><label class="field">Bucket height: <b>${transient.height}%</b><input id="height" type="range" min="0" max="100" value="${transient.height}"></label><p class="result ${transient.height<=25?"safe":""}">${transient.height<=25?"Lower travel position reduces instability risk.":"Higher load position increases instability and rollover risk."}</p></article><article class="activity"><span class="eyebrow">Challenge 3</span><h3>Load-mass calculator</h3><div class="calc-grid">${["volume","density","fill","capacity"].map(k=>`<label class="field">${k}<input type="number" step="0.1" data-calc="${k}" value="${transient.calc[k]}"></label>`).join("")}</div>${calcResult()}</article><article class="activity"><span class="eyebrow">Challenge 4</span><h3>Safe shutdown sequence</h3><p>Select steps in order.</p><div class="sequence-progress">${transient.sequence.length?transient.sequence.map(x=>esc(x)).join(" → "):"Start the sequence"}</div><div class="sequence">${["Park on stable area","Lower implement","Neutralise controls","Apply park brake","Idle as required","Shut down and isolate"].map((x,i)=>`<button data-seq="${i}" ${transient.sequence.includes(x)?"disabled":""}>${x}</button>`).join("")}</div></article></div></section>`,
theory:()=>`<section class="content narrow"><div class="section-intro"><span class="eyebrow">Summative knowledge assessment</span><h2>100% mastery required</h2><p>Answer every question. Incorrect answers are identified for targeted review and reassessment.</p></div><div class="banner"><b>Attempt result</b><span>${score()}/16 correct</span><strong class="badge ${theoryPassed()?"pass":""}">${theoryPassed()?"Mastery achieved":"Not yet achieved"}</strong></div>${questions.map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${q[0]}</legend>${q[1].map((a,j)=>`<label class="${state.submitted?(j===q[2]?"correct":state.answers[i]===j?"incorrect":""):""}"><input type="radio" name="q${i}" value="${j}" ${state.answers[i]===j?"checked":""}>${a}</label>`).join("")}${state.submitted?`<small class="reference">Source mapping: ${q[3]}</small>`:""}</fieldset>`).join("")}<button class="primary submit" id="submitTheory">${state.submitted?"Resubmit assessment":"Submit assessment"}</button></section>`,
practical:()=>`<section class="content"><div class="section-intro"><span class="eyebrow">Credentialed assessor use only</span><h2>Two observed operating occasions</h2><p>Use at least two different material types. All tasks must be observed in a safe, sector-relevant environment using current procedures and OEM information.</p></div>${state.occasions.map((o,i)=>occasion(i,o)).join("")}</section>`,
evidence:()=>`<section class="content narrow"><div class="decision"><span class="eyebrow">Evidence gate</span><h2>${theoryPassed()&&practicalPassed()?"Ready for assessor judgement":"Evidence incomplete"}</h2><p>This status is not a competency outcome. The assessor must authenticate, validate and record the final decision in MyneSight’s controlled system.</p></div><div class="evidence-grid"><article><b>Theory</b><h2>${score()}/16</h2><small>100% required</small></article><article><b>Occasion 1</b><h2>${occasionComplete(state.occasions[0])?"Complete":"Pending"}</h2></article><article><b>Occasion 2</b><h2>${occasionComplete(state.occasions[1])?"Complete":"Pending"}</h2></article><article><b>Materials</b><h2>${new Set(state.occasions.map(o=>o.material.trim().toLowerCase()).filter(Boolean)).size}/2</h2></article></div><div class="actions"><button class="primary" id="export">Download evidence JSON</button><button id="print">Print assessor record</button></div><div class="warning"><strong>Privacy</strong><p>Progress remains in this browser. Transfer downloaded evidence into the approved RTO records system; do not commit candidate records to GitHub.</p></div></section>`,
sources:()=>`<section class="content narrow"><div class="section-intro"><span class="eyebrow">Controlled-source register</span><h2>Legislation and references</h2><p>Queensland requirements are contextualised here. MyneSight must verify currency and applicability before delivery.</p></div>${sources.map((s,i)=>`<article class="source"><div><strong>${s[0]}</strong><p class="muted">${s[1]}</p></div><b>Ref ${String(i+1).padStart(2,"0")}</b></article>`).join("")}<div class="warning"><strong>Document-control rule</strong><p>Model-specific values for WA500-6, WA800-3, WA1200-6 and LeTourneau L2350 must come from the approved OEM manual and site procedures for the exact machine and configuration.</p></div></section>`
};
function calcResult(){const c=transient.calc,m=c.volume*c.density*c.fill/100,safe=m<=c.capacity;return `<div class="result ${safe?"safe":""}"><strong>${m.toFixed(2)} t</strong> · ${safe?"within":"above"} entered capacity</div><button id="checkCalc">Check calculation</button>`}
function occasion(i,o){return `<article class="observation" data-occ="${i}"><div class="observation-head"><div><span class="eyebrow">Observed occasion ${i+1}</span><h3>Practical record</h3></div><b class="status ${occasionComplete(o)?"pass":""}">${occasionComplete(o)?"Complete":"Incomplete"}</b></div><div class="form-grid">${["date","location","serial","material","assessor"].map(k=>`<label class="field">${k}<input data-field="${k}" type="${k==="date"?"date":"text"}" value="${esc(o[k])}"></label>`).join("")}<label class="field">machine<select data-field="machine">${machines.map(x=>`<option ${o.machine===x?"selected":""}>${x}</option>`).join("")}</select></label></div><div class="warning">Record the exact machine and serial. Verify capacity and procedures against approved OEM documentation.</div><div class="tasks">${tasks.map((t,j)=>`<label><input type="checkbox" data-task="${j}" ${o.tasks[j]?"checked":""}><span>${String(j+1).padStart(2,"0")}</span>${t}</label>`).join("")}</div><label class="field">Assessor comments<textarea data-field="comments">${esc(o.comments)}</textarea></label><label class="critical"><input type="checkbox" data-field="critical" ${o.critical?"checked":""}>Critical safety failure recorded</label><div class="declarations"><label><input type="checkbox" data-field="candidateDeclaration" ${o.candidateDeclaration?"checked":""}>Candidate declares the evidence is their own work.</label><label><input type="checkbox" data-field="assessorDeclaration" ${o.assessorDeclaration?"checked":""}>Assessor confirms direct observation and evidence authenticity.</label></div></article>`}
function award(id,msg){if(!state.badges.includes(id))state.badges.push(id);save();notice(msg)}
function bind(){
 document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
 document.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>{const i=+b.dataset.module;state.completed=state.completed.includes(i)?state.completed.filter(x=>x!==i):[...state.completed,i];save();render()});
 document.querySelectorAll(".question input").forEach(x=>x.onchange=()=>{state.answers[+x.name.slice(1)]=+x.value;state.submitted=false;save()});
 const submit=document.querySelector("#submitTheory");if(submit)submit.onclick=()=>{state.submitted=true;save();render();notice(theoryPassed()?"Theory mastery achieved. Practical evidence remains required.":"Review highlighted answers and try again.")};
 document.querySelectorAll("[data-hotspot]").forEach(b=>b.onclick=()=>{const i=+b.dataset.hotspot;if(!transient.hotspots.includes(i))transient.hotspots.push(i);if(transient.hotspots.length===4)award("hotspots","Pre-start hotspot challenge complete.");render()});
 const h=document.querySelector("#height");if(h)h.oninput=()=>{transient.height=+h.value;if(transient.height<=25)award("stability","Safe bucket-height zone identified.");render()};
 document.querySelectorAll("[data-calc]").forEach(x=>x.onchange=()=>{transient.calc[x.dataset.calc]=+x.value;render()});const ck=document.querySelector("#checkCalc");if(ck)ck.onclick=()=>award("calculation","Load mass calculated and checked against capacity.");
 const order=["Park on stable area","Lower implement","Neutralise controls","Apply park brake","Idle as required","Shut down and isolate"];document.querySelectorAll("[data-seq]").forEach(b=>b.onclick=()=>{const x=order[+b.dataset.seq];if(x===order[transient.sequence.length]){transient.sequence.push(x);if(transient.sequence.length===order.length)award("shutdown","Shutdown sequence complete.")}else{transient.sequence=[];notice("Sequence reset. Start with parking on a stable area.")}render()});
 document.querySelectorAll("[data-occ]").forEach(box=>{const i=+box.dataset.occ;box.querySelectorAll("[data-field]").forEach(x=>x.onchange=()=>{state.occasions[i][x.dataset.field]=x.type==="checkbox"?x.checked:x.value;save();render()});box.querySelectorAll("[data-task]").forEach(x=>x.onchange=()=>{state.occasions[i].tasks[+x.dataset.task]=x.checked;save();render()})});
 const ex=document.querySelector("#export");if(ex)ex.onclick=exportRecord;const pr=document.querySelector("#print");if(pr)pr.onclick=()=>window.print()
}
function exportRecord(){const record={schema:"RIIMPO321F-assessment-record-v1",generated:new Date().toISOString(),rto:{name:"MyneSight Pty Ltd",code:"31900"},trainingProduct:"RIIMPO321F Release 3",jurisdiction:"Queensland",candidate:state.candidate,theory:{score:score(),total:16,mastery:theoryPassed(),answers:state.answers},practical:state.occasions.map((o,i)=>({occasion:i+1,...o,complete:occasionComplete(o)})),readyForAssessorJudgement:theoryPassed()&&practicalPassed(),warning:"A credentialed assessor must verify authenticity, evidence and final judgement in the RTO assessment system."};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:"application/json"}));a.download=`RIIMPO321F-${state.candidate.id||"candidate"}-assessment-record.json`;a.click();URL.revokeObjectURL(a.href);notice("Assessment record downloaded.")}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelector("#candidateName").value=state.candidate.name;document.querySelector("#studentId").value=state.candidate.id;document.querySelector("#candidateName").oninput=e=>{state.candidate.name=e.target.value;save()};document.querySelector("#studentId").oninput=e=>{state.candidate.id=e.target.value;save()};go(state.view);
